services:
  postgres:
    image: postgres:15
    container_name: recanto-postgres
    restart: always
    environment:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init_data.sql:/docker-entrypoint-initdb.d/init_data.sql
    networks:
      - recanto-das-palmeiras-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: recanto-das-palmeiras-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - recanto-das-palmeiras-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: recanto-pgadmin
    restart: always
    environment:
      - .env
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_LISTEN_PORT}"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - recanto-das-palmeiras-network

networks:
  recanto-das-palmeiras-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local