-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cliente
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    telefone character varying(20) COLLATE pg_catalog."default",
    cpf_cnpj character varying(20) COLLATE pg_catalog."default",
    senha character varying(255) COLLATE pg_catalog."default",
    ativo boolean NOT NULL DEFAULT true,
    CONSTRAINT cliente_pkey PRIMARY KEY (id),
    CONSTRAINT cliente_cpf_cnpj_key UNIQUE (cpf_cnpj),
    CONSTRAINT cliente_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.produto
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descricao character varying(255) COLLATE pg_catalog."default",
    preco numeric(10, 2) NOT NULL,
    quantidade integer NOT NULL DEFAULT 0,
    imagem_url character varying(100) COLLATE pg_catalog."default",
    ativo boolean NOT NULL DEFAULT true,
    CONSTRAINT produto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    cargo character varying(20) COLLATE pg_catalog."default" NOT NULL,
    senha character varying(255) COLLATE pg_catalog."default" NOT NULL,
    ativo boolean NOT NULL DEFAULT true,
    CONSTRAINT usuario_pkey PRIMARY KEY (id),
    CONSTRAINT usuario_email_key UNIQUE (email)
);
END;