name: Backend CI/CD to Elastic Beanstalk (JAR Deployment)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

env:
 AWS_REGION: us-east-1
 EB_APPLICATION_NAME: recanto-das-palmeiras-app
 EB_ENVIRONMENT_NAME: Recanto-das-palmeiras-app-env-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw
        working-directory: ./backend

      - name: Build and Package Backend
        run: |
          ./mvnw clean install -DskipTests
          mv target/*.jar target/app.jar
        working-directory: ./backend

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create deployment package (ZIP)
        run: |
          zip -j backend-deploy.zip target/app.jar
          ls -l backend-deploy.zip
        working-directory: ./backend

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.EB_APPLICATION_NAME }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          version_label: ${{ github.sha }}
          region: ${{ env.AWS_REGION }}
          deployment_package: backend-deploy.zip